version: 2
jobs:
  build:
    docker:
      - image: k4zuki/pandocker-alpine
    steps:
      - checkout
      - run:
          name: env variables
          command: |
            echo "export DATE=`date +%Y-%m%b-%d`" >> $BASH_ENV
            echo "export SHORT_HASH=${CIRCLE_SHA1:0:7}" >> $BASH_ENV
            source $BASH_ENV
            echo "export BUILD=build-$CIRCLE_BUILD_NUM-$CIRCLE_BRANCH-$DATE-$SHORT_HASH" >> $BASH_ENV
            source $BASH_ENV
            echo "SHORT_HASH=" $SHORT_HASH
            echo "DATE=" $DATE
            echo "BUILD=" $BUILD
      - run:
          name: get submodules
          command: git submodule update --init; echo $DATE
      - run:
          name: Prepare ghr
          command: |
            mkdir build
            cd build
            wget -c https://github.com/tcnksm/ghr/releases/download/v0.5.4/ghr_v0.5.4_linux_amd64.zip
            unzip ghr_v0.5.4_linux_amd64.zip
            cp ./ghr /usr/local/bin
      - run:
          name: Prepare QR code for this build
          command: |
            make initdir
            pip3 install qrcode
            URL=https://github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/releases/download
            qr $URL/$BUILD/Pandocker-Docs-$CIRCLE_BRANCH-$SHORT_HASH.pdf > images/QRcode.png
      - run:
          name: Make HTML
          command: |
            make initdir html BRANCH=$CIRCLE_BRANCH HASH=$SHORT_HASH
      - run:
          name: Make PDF
          command: |
            make initdir pdf BRANCH=$CIRCLE_BRANCH HASH=$SHORT_HASH
      - run:
          name: Make DOCX
          command: |
            make initdir docx BRANCH=$CIRCLE_BRANCH HASH=$SHORT_HASH
      - run:
          name: Deploy preparation
          command: |
            mkdir deploy
            mv Out/*.html deploy/
            mv Out/*.pdf deploy/
            mv Out/*.docx deploy/
      - run:
          name: Deploy
          command: |
            ghr -replace -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME $BUILD deploy/
